### ISSUE TITLE
is it possible to change climatisation_target_temperature

### ISSUE THREAD

**Issue by tasisale** [skodaconnect/skodaconnect#113]
is it possible to change the value from climatisation_target_temperature  via API at this moment?
will this to work with a Enyaq?

regards
simon

**Comment by dvx76** [comment]
The `set_climater` service should support this. That being set I recall some discussion on Discord about issues with it. 

```
service: skodaconnect.set_climater
data:
  temp: 22
```

**Comment by dvx76** [comment]
Fixed by #111 , I think

**Comment by tasisale** [comment]
It is required that skodaconnect (the library I use) supports that. Currently it's not supported there, is that right?
i will not get it work.
have new rasp. + SD + pip install and send data, nothing will do.

can you help?

**Comment by tasisale** [comment]
> You will either need to apply the changes from #111 manually or wait until the PR is merged and the integration updated to a new version.

Is there a time window for this or in the future 2024?

regards
simon

**Comment by dvx76** [comment]
We don't have a fixed release schedule but I'd hope we push out an update in February.

**Comment by dvx76** [comment]
Closing as fixed by #111
