### ISSUE TITLE
Skoda Connect Lite support ?

### ISSUE THREAD

**Issue by AMajland** [skodaconnect/skodaconnect#117]
https://www.skoda-auto.com/connectivity/skoda-connect-lite

I have a Kodiaq and a Enyaq where i use this Skoda Connect integration. But i jus saw a commercial for the  above Skoda Connect Lite that consists of an ODB dongle and a seperate Skoda Lite App (Has the MySkoda and My Skoda Essential already - and only the later support both cars.)

But would be interested in getting our older Citigo into HA as well

DataPlug for Connect LITE 000051629A (<40€in the Czech Republic)

**Comment by dvx76** [comment]
This might be possible if the Skoda Lite App uses the same or a similar set of API endpoints as the other Skoda app. It would require someone to purchase the service and provide detailed traces of traffic to/from the Lite app.

**Comment by AMajland** [comment]
I've ordered the OBD dongle yesterday - but will probably need a rather detailed instruction in how to trace traffic to/from the app.

**Comment by AMajland** [comment]
I've receved the dongle but the cars is not home before the weekend ....

**Comment by AMajland** [comment]
Well - i was mislead by marketing. 

The dongle is just an bluetooth odb interface :-( and the Skoda Connect Lite app is not worth anything unless you are actively using it in the car. 

Sorry for the noise, and this can be closes as way outside the scope of skodaconnect

**Comment by dvx76** [comment]
Thanks for following up. Sorry it didn't work out for you.
