### ISSUE TITLE
i have use fhempy to use your skoda integration for me...

### ISSUE THREAD

**Issue by tasisale** [skodaconnect/skodaconnect#122]
... it works fine and all will work, but i can not set the climatisation_target_temperature for my Skoda Enyaq IV.

can you help?
--
`2024.03.08 18:16:29.964 4: BindingsIo (fhempy_local): <<< WS: {"argsh":{},"args":["my_skoda","climatisation_target_temperature","23.0"],"defargs":["my_skoda","fhempy","skodaconnect","xxxx@xxxx.de","hierstehtdasPassword","SPin"],"msgtype":"function","PYTHONTYPE":"skodaconnect","NAME":"my_skoda","function":"Set","id":69113115,"FHEMPYTYPE":"skodaconnect","defargsh":{}}
2024.03.08 18:16:29.964 5: DevIo_SimpleWrite fhempy_local: 7b226172677368223a7b7d2c2261726773223a5b226d795f736b6f6461222c22636c696d617469736174696f6e5f7461726765745f74656d7065726174757265222c2232332e30225d2c2264656661726773223a5b226d795f736b6f6461222c226668656d7079222c22736b6f6461636f6e6e656374222c2273696d6f6e4064696568697070732e6465222c2238366d59486d3f727162244b5a21437552753871222c2231363335225d2c226d736774797065223a2266756e6374696f6e222c22505954484f4e54595045223a22736b6f6461636f6e6e656374222c224e414d45223a226d795f736b6f6461222c2266756e6374696f6e223a22536574222c226964223a36393131333131352c224648454d505954595045223a22736b6f6461636f6e6e656374222c226465666172677368223a7b7d7d
2024.03.08 18:16:29.965 4: BindingsIo (fhempy_local): 1 - start fhempyFunction: my_skoda => Set (69113115)
2024.03.08 18:16:29.966 4: BindingsIo (fhempy_local): >>> WS: {"argsh": {}, "args": ["my_skoda", "climatisation_target_temperature", "23.0"], "defargs": ["my_skoda", "fhempy", "skodaconnect", "xxxx@xxxx.de", "hierstehtdasPassword", "SPin"], "msgtype": "function", "PYTHONTYPE": "skodaconnect", "NAME": "my_skoda", "function": "Set", "id": 69113115, "FHEMPYTYPE": "skodaconnect", "defargsh": {}, "finished": 1, "returnval": ""}
2024.03.08 18:16:29.966 5: BindingsIo_storeMessage: {"argsh": {}, "args": ["my_skoda", "climatisation_target_temperature", "23.0"], "defargs": ["my_skoda", "fhempy", "skodaconnect", "xxxx@xxxx.de", "hierstehtdasPassword", "SPin"], "msgtype": "function", "PYTHONTYPE": "skodaconnect", "NAME": "my_skoda", "function": "Set", "id": 69113115, "FHEMPYTYPE": "skodaconnect", "defargsh": {}, "finished": 1, "returnval": ""}
2024.03.08 18:16:29.966 4: BindingsIo (fhempy_local): 1 - end fhempyFunction: my_skoda => Set (69113115) - result: `

regards
simon

**Comment by dvx76** [comment]
Sorry I don't really know what to do with this or what information to extract from the provided log. I had to google what fhempy and fhem even are.

What I can tell you is that when used with the homeassistant-skodaconnect the `climatisation_target_temperature` is a sensor (so read only) and setting it is done through a service call called `set_climater`, which ends up calling `set_climatisation_temp`  https://github.com/skodaconnect/skodaconnect/blob/bc9371520bf329e6f039844bf1ab92783d3c4ecb/skodaconnect/vehicle.py#L776

You should be able to test this and play around with this by starting with the code in `example.py` in this project. https://github.com/skodaconnect/skodaconnect/blob/bc9371520bf329e6f039844bf1ab92783d3c4ecb/example/example.py#L327
