### ISSUE TITLE
Error with the isoformat string

### ISSUE THREAD

**Issue by SW-OS** [skodaconnect/skodaconnect#123]
Hello,

I'm  using your script successfully.. thanks for your work.

But since version 1.3.10 I got an error concerning the iosformat  string. 
Reinstallung version 1.3.9 the error was not seen anymore.

I renamed the example.py to connection_org.py and entered the password and account. Subsequently I started the script from the command shell on a raspberry like: python3 connection_org.py and got the following output:

  File "connect_org.py", line 358, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "connect_org.py", line 247, in main
    print(f'\tstr_state: {instrument.str_state} - state: {instrument.state}')
  File "/usr/local/lib/python3.7/dist-packages/skodaconnect/dashboard.py", line 123, in str_state
    return f'{self.state}'
  File "/usr/local/lib/python3.7/dist-packages/skodaconnect/dashboard.py", line 127, in state
    val = super().state
  File "/usr/local/lib/python3.7/dist-packages/skodaconnect/dashboard.py", line 58, in state
    if hasattr(self.vehicle, self.attr):
  File "/usr/local/lib/python3.7/dist-packages/skodaconnect/vehicle.py", line 1542, in last_connected
    last_connected = datetime.fromisoformat(last_connected_utc)
ValueError: Invalid isoformat string: '2024-04-09T05:10:13.029Z'

Thanks for any tipps

Stefan

**Comment by dvx76** [comment]
See #109. This happens on Python 3.9 or below. `datetime.fromisoformat` was apparently changed in Python 3.10 or 3.11. We need to update the `requires-python` in this pyproject.toml to reflect that.

**Comment by SW-OS** [comment]
Hello,

just now, I installed the new 1.3.11 version, but I got the same error as before.

Sorry, but 1.3.11 has still the isostring problem.

Thanks

Stefan

**Comment by dvx76** [comment]
There is no fix, you just need to update your Python version. #125 just bumps the minimum Python version required for this package to 3.11.

**Comment by SW-OS** [comment]
Sorry for my misunderstanding...
Unfortunately I cannot influence the Python version because the script runs on a commercial web server. The company won't update Python for a few months.
Isn't there a possibility that the "timezone format" is processed depending on the Python version in your Scripts (i.e. vehicle.py)

Thanks

Stefan

**Comment by dvx76** [comment]
\+ @badrpc FYI if you have any ideas or suggestions

The primary use-case for this project is to be used in Homeassistant, through https://github.com/skodaconnect/homeassistant-skodaconnect so it's going to track the Python versions/requirements from HA, which is currently 3.11 (or even 3.12) I think.

@SW-OS if you can propose a fix which still resolved https://github.com/skodaconnect/homeassistant-skodaconnect/issues/225 / https://github.com/skodaconnect/skodaconnect/pull/99 but also works on Python 3.9 that would be ok for me.

**Comment by badrpc** [comment]
As I mentioned in https://github.com/skodaconnect/skodaconnect/pull/99#issue-1966213660 `datetime.strptime(last_connected_utc,'%Y-%m-%dT%H:%M:%SZ').astimezone(timezone.utc)` can be used instead of `datetime.fromisoformat(...)`. I believe this works in Python 3.9. I don't think it is worth making this conditional on Python version, but probably deserves a comment explaining the problem.

**Comment by dvx76** [comment]
@SW-OS are you able to validate if this works for you?

**Comment by SW-OS** [comment]
I was following the solution of https://pypi.org/project/backports-datetime-fromisoformat/

This worked perfect without changing your scripts (i.e. vehicle.py) within the module.....

I had only to install the package and to add two lines for importing in the head of the main script....

In my mind the best solution......

Regards
