### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by Farfar** [skodaconnect/skodaconnect#74]
Hi @lendy007,

I couldn't find any other way of contacting you.
To further improve and maintain this code I need to be able to add new members.
Easiest way forward, since maintainers probably will change in the future as well, is if you can transfer ownership to me so I can add new members as well.

-BR

**Comment by lendy007** [comment]
Hi @Farfar - I have tried to transfer ownership, but I got this error - Farfar already has a repository in the lendy007/skodaconnect network

**Comment by Farfar** [comment]
I didn't consider the seat forks. I have created a ticket to extract the fork into it's own network. When it's done you are welcome to try again.

**Comment by dvx76** [comment]
Let's transfer to an Org instead. I believe @WebSpider is creating one.

**Comment by WebSpider** [comment]
https://github.com/skodaconnect

I invited @Farfar as co-owner

**Comment by Farfar** [comment]
Excellent! @lendy007 please transfer into above organization. And if you still want to be part of the development just say the word and we'll send an invite.

**Comment by lendy007** [comment]
@WebSpider - when i try to that org I am getting this - You don’t have the permission to create public repositories on skodaconnect

**Comment by Farfar** [comment]
Seems you have to be an admin of organization to be able to transfer the repo. The seatconnect fork should be fixed now so you should be able to transfer the repo to me and then I can transfer it to the org.
Or I invite you to the organization.

**Comment by lendy007** [comment]
Ok, I've transfered it

**Comment by Farfar** [comment]
Great! Waiting for email from GitHub to complete transfer.
