### ISSUE TITLE
please help to add into fhem

### ISSUE THREAD

**Issue by tasisale** [skodaconnect/skodaconnect#97]
can you help me to use this in fhem.
i have install it with putty and pip, but how i can use it?
sorry, i not a expert user ,-)

**Comment by jfmennedy** [comment]
You cannot use this library directly in fhem. This library is used by fhem-module fhempy as base to integrate skodaconnect in fhem. If you installed skodaconnect now on your system you can run e.g. the example.py to check if the readings you want to see in fhem are exposed by this library. 

You might create a virtual environement on your system by using "python -m venv venv" and install skodaconnect to it by using "pip install skodaconnect". When it is done you modify in example.py username and password and run example.py 

You will get some output with all readings received by this library. If you do not find the reading you want (in your case you asked for service/inspection date) you wont get this reading in fhem either.

**Comment by tasisale** [comment]
ok, thx i have done this, the same response without the need data.
so it will not share, thx again.
